script_game_start = 0
script_use_item = 1
script_shield_item_set_banner = 2
script_check_creating_ladder_dust_effect = 3
script_add_troop_to_cur_tableau = 4
script_add_troop_to_cur_tableau_for_character = 5
script_add_troop_to_cur_tableau_for_inventory = 6
script_add_troop_to_cur_tableau_for_profile = 7
script_add_troop_to_cur_tableau_for_retirement = 8
script_add_troop_to_cur_tableau_for_party = 9
script_draw_banner_to_region = 10
script_get_troop_custom_banner_num_positionings = 11
script_agent_troop_get_banner_mesh = 12
script_get_custom_banner_charge_type_position_scale_color = 13
script_update_party_creation_random_limits = 14


